name: Deploy UI to CloudRun

on:
  workflow_call:
    inputs:
      gcp_region:
        required: true
        type: string
      gcp_project_id:
        required: true
        type: string
      environment:
        required: true
        type: string
      fpm_image_repo:
        required: true
        type: string
      nginx_image_repo:
        required: true
        type: string        
      image_tag:
        required: true
        type: string
      service_name:
        required: true
        type: string
      port:
        required: true
        type: string
      bucket_name:
        required: true
        type: string
      nginx_cpu:  
        required: false
        type: string
        default: '.5'
      nginx_memory:
        required: false
        type: string
        default: '256Mi'
      fpm_cpu:
        required: false
        type: string
        default: '.5'
      fpm_memory:
        required: false
        type: string
        default: '768Mi' 
      project_name:
        required: false
        type: string
      env:
        required: false
        type: string        
    



    secrets:
      gcp_workload_identity_provider:
        required: true
      gcp_service_account:
        required: true

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.gcp_workload_identity_provider }}
          service_account: ${{ secrets.gcp_service_account }}

      - name: Create Storage Bucket
        run: |
          if ! gcloud storage buckets describe gs://${{ inputs.bucket_name }} &>/dev/null; then
            echo "Bucket does not exist. Creating gs://${{ inputs.bucket_name }}..."
            gcloud storage buckets create gs://${{ inputs.bucket_name }} --location=${{ inputs.gcp_region }}
          else
            echo "Bucket gs://${{ inputs.bucket_name }} already exists."
          fi    

      - name: Create Cache Bucket
        run: |
          if ! gcloud storage buckets describe gs://${{ inputs.bucket_name }}-cache &>/dev/null; then
            echo "Bucket does not exist. Creating gs://${{ inputs.bucket_name }}-cache..."
            gcloud storage buckets create gs://${{ inputs.bucket_name }}-cache --location=${{ inputs.gcp_region }}
          else
            echo "Bucket gs://${{ inputs.bucket_name }}-cache already exists."
          fi          

      - name: Deploy to Cloud Run
        run: |
          NGINX_IMAGE_NAME="asia-southeast1-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.nginx_image_repo }}:${{ inputs.image_tag }}"
          FPM_IMAGE_NAME="asia-southeast1-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.fpm_image_repo }}:${{ inputs.image_tag }}"


          # If project_name AND env are provided, construct the network/subnet names.
          # Otherwise, fall back to using 'default' for both.
          if [[ -n "${{ inputs.project_name }}" && -n "${{ inputs.env }}" ]]; then
            echo "Constructing network and subnet names from 'project_name' and 'env' inputs."
            NETWORK_NAME="projects/${{ inputs.project_name }}-hostnet-prod-1/global/networks/${{ inputs.project_name }}-vpc-${{ inputs.env }}-host-1"
            SUBNET_NAME="projects/${{ inputs.project_name }}-hostnet-prod-1/regions/asia-southeast1/subnetworks/${{ inputs.project_name }}-${{ inputs.env }}-priv-sub-1"
          else
            echo "'project_name' and/or 'env' not provided. Falling back to 'default' network and subnet."
            NETWORK_NAME="default"
            SUBNET_NAME="default"
          fi


          gcloud run deploy ${{ inputs.service_name }} \
            --platform managed \
            --execution-environment=gen2 \
            --region ${{ inputs.gcp_region }} \
            --project ${{ inputs.gcp_project_id }} \
            --network $NETWORK_NAME \
            --subnet $SUBNET_NAME \
            --vpc-egress="private-ranges-only" \
            --allow-unauthenticated \
            --add-volume name=storage-volume,type=cloud-storage,bucket=${{ inputs.bucket_name }} \
            --add-volume name=cache-volume,type=cloud-storage,bucket=${{ inputs.bucket_name }}-cache \
            --container nginx --image=$NGINX_IMAGE_NAME --port 8080 --memory ${{ inputs.nginx_memory }} --cpu ${{ inputs.nginx_cpu }} --add-volume-mount volume=storage-volume,mount-path=/var/www/html/storage \
            --container fpm --image=$FPM_IMAGE_NAME --memory ${{ inputs.fpm_memory }} --cpu ${{ inputs.fpm_cpu }} --add-volume-mount volume=storage-volume,mount-path=/var/www/html/storage --add-volume-mount volume=cache-volume,mount-path=/var/www/html/bootstrap/cache/data


      - name: Create Cloud Run Job
        run: |
          FPM_IMAGE_NAME="asia-southeast1-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.fpm_image_repo }}:${{ inputs.image_tag }}"

          # If project_name AND env are provided, construct the network/subnet names.
          # Otherwise, fall back to using 'default' for both.
          if [[ -n "${{ inputs.project_name }}" && -n "${{ inputs.env }}" ]]; then
            echo "Constructing network and subnet names from 'project_name' and 'env' inputs."
            NETWORK_NAME="projects/${{ inputs.project_name }}-hostnet-prod-1/global/networks/${{ inputs.project_name }}-vpc-${{ inputs.env }}-host-1"
            SUBNET_NAME="projects/${{ inputs.project_name }}-hostnet-prod-1/regions/asia-southeast1/subnetworks/${{ inputs.project_name }}-${{ inputs.env }}-priv-sub-1"
          else
            echo "'project_name' and/or 'env' not provided. Falling back to 'default' network and subnet."
            NETWORK_NAME="default"
            SUBNET_NAME="default"
          fi
          # --- End of Logic ---

          # Check if the job already exists
          echo "Checking for existing job: ${{ inputs.service_name }}-job"
          if gcloud run jobs describe ${{ inputs.service_name }}-job --region ${{ inputs.gcp_region }} --project ${{ inputs.gcp_project_id }} &>/dev/null;
          then
            echo "Job found. Updating..."
            # Update the job with new parameters
            gcloud run jobs update ${{ inputs.service_name }}-job \
              --region ${{ inputs.gcp_region }} \
              --network $NETWORK_NAME \
              --subnet $SUBNET_NAME \
              --vpc-egress="private-ranges-only" \
              --image $FPM_IMAGE_NAME \
              --project ${{ inputs.gcp_project_id }} \
              --command "null" \
              --args "null" \
              --cpu 1 \
              --memory 512Mi \
              --max-retries 0 \
              --tasks 1 \
              --task-timeout 300s
          else
            echo "Job not found. Creating..."
            # Create a new job
            gcloud run jobs create ${{ inputs.service_name }}-job \
            --region ${{ inputs.gcp_region }} \
            --network $NETWORK_NAME \
            --subnet $SUBNET_NAME \
            --vpc-egress="private-ranges-only" \
            --image $FPM_IMAGE_NAME \
            --project ${{ inputs.gcp_project_id }} \
            --command "null" \
            --args "null" \
            --cpu 1 \
            --memory 512Mi \
            --max-retries 0 \
            --tasks 1 \
            --task-timeout 300s
          fi